-
  name: Install Docker
  hosts: my_servers
  become: yes
  tasks:

    - name: Add Docker repo on RedHat
      command: dnf config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo
      when: ansible_facts["distribution"] == 'RedHat'

    - name: Install docker on RedHat
      package:
        name: docker-ce
        state: present
      when: ansible_facts["distribution"] == 'RedHat'

    - name: Install docker on Amazon Linux 2023
      package:
        name: docker
        state: present
      when: ansible_facts["distribution"] == 'Amazon'

    - name: Install docker on Ubuntu
      package:
        name: docker.io
        state: present
      when: ansible_facts["distribution"] == 'Ubuntu'

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
